
DELIMITER = '|'
END_OF_MESSAGE = '\n'

YES = 1
NO = 0

# MESSAGES
REMATCH = "REMATCH"
WAITING = "WAITING"
CONNECTION_LOST = "CONNECTION_LOST"

MESSAGE_LOGIN = "LOGIN"
MESSAGE_LOGGED = "LOGGED"
MESSAGE_PING = "PING"
MESSAGE_WAITING = "WAITING"
MESSAGE_CANCEL = "CANCEL"
MESSAGE_START = "START"
MESSAGE_TURN = "TURN"
MESSAGE_GAME = "GAME"
MESSAGE_RESULT = "RESULT"
MESSAGE_REMATCH_YES = f"{REMATCH}{DELIMITER}{YES}"
MESSAGE_REMATCH_NO = f"{REMATCH}{DELIMITER}{NO}"

# COLORS
RED = "#cf2121"
BLUE = "#6d59ff"
GRAY = "#946f6f"

# Timeout
CONNECTION_TIMEOUT = 1  # 1 second
HEARTBEAT_TIME = 0.25   # 250 ms
HEARTBEAT_PER_TIMEOUT = 4
SECONDS_IN_MINUTE = 60

# Other
NUMBER_OF_FIELDS = 9

# Texts
WINDOW_TITLE = "TIC-TAC-TOE"



