
DELIMITER = '|'
END_OF_MESSAGE = '\n'

YES = 1
NO = 0

# MESSAGES
PING = "PING"
LOGIN = "LOGIN"
CANCEL = "CANCEL"
START = "START"
REMATCH = "REMATCH"
WAITING = "WAITING"
CONNECTION_LOST = "CONNECTION_LOST"

MESSAGE_PING = f"{PING}{END_OF_MESSAGE}"
MESSAGE_CANCEL = f"{CANCEL}{END_OF_MESSAGE}"
MESSAGE_START = f"{START}{END_OF_MESSAGE}"
MESSAGE_REMATCH_YES = f"{REMATCH}{DELIMITER}{YES}{END_OF_MESSAGE}"
MESSAGE_REMATCH_NO = f"{REMATCH}{DELIMITER}{NO}{END_OF_MESSAGE}"

# COLORS
RED = "#cf2121"
BLUE = "#6d59ff"
GRAY = "#946f6f"

